-- #0124: this migration's up.sql is now a documented no-op (see that
-- file's comment) — its effect was folded back into 000014's index
-- definition rather than kept as a separate widen-then-narrow step. Nothing
-- to reverse.
