-- #0124 folds this migration's effect back into 000014's index definition,
-- per this issue's acceptance criterion ("migrations/000016 is folded back
-- into 000014's index definition or deleted outright"). Deleting the file
-- outright was considered and rejected: internal/db/docs_parity_test.go's
-- verifyContiguous (#0083) requires migrations/ to be a gap-free
-- 000001-prefixed sequence on disk, so removing this slot would force
-- renumbering every migration from 000017 onward — six file pairs, plus
-- every doc/code comment naming migrations/000017 through migrations/000022
-- by number (worker.go, worker_store.go, campaigns.go, docs/database.md,
-- this issue's own dependencies #0126) — for no behavioral gain. Folding in
-- place (this file becomes a documented no-op) gets the same outcome
-- ("000016's widened idx_email_events_soft_bounce no longer exists as a
-- separate migration step") without that cascade.
--
-- What used to be here: #0016 originally widened 000014's partial index
-- idx_email_events_soft_bounce (DROP + CREATE, #0109's Undetermined/subtype
-- predicate). #0124 removes the windowed soft-bounce count entirely — the
-- suppression rule is now a consecutive streak on
-- subscribers.soft_bounce_streak (migration 000010), counted incrementally
-- rather than re-queried from email_events — so that index has no query
-- left to serve. 000014's own CREATE INDEX statement was edited directly
-- (greenfield, CLAUDE.md §1: it has never been applied to a database anyone
-- cares about) to go straight to idx_email_events_recipient_time, the
-- index #0124 actually needs (GET /admin/deliverability's per-address
-- history, sorted by recency) — so there is nothing left for this slot to
-- do. See migrations/000014_create_email_events.up.sql's comment and
-- issues/0124.md's Notes.
